const BANJARA_SENTENCES = [
    { "id": 1, "english": "Where do you work?", "banjara": "Tu kai kaam karrochi?" },
    { "id": 2, "english": "I am going to the village tomorrow.", "banjara": "me xavar taanden jaayevalo chu" },
    { "id": 3, "english": "This food is very tasty.", "banjara": "ee daliya ghano aacho laago." },
    { "id": 4, "english": "How much for this shirt?", "banjara": "ee jhiglare kai bhaav che?" },
    { "id": 5, "english": "My stomach is aching.", "banjara": "Maaro peetemai dookroche" },
    { "id": 6, "english": "It is raining heavily outside.", "banjara": "baar ghano paani padro che." },
    { "id": 7, "english": "Can you give me some water?", "banjara": "mann channik paani dechi ge?" },
    { "id": 8, "english": "I don't have money.", "banjara": "maar kan peesa cheeni" },
    { "id": 9, "english": "Let's go to the market.", "banjara": "chal, dukaanen jaama" },
    { "id": 10, "english": "The bus is late today.", "banjara": "aaj bus deer eeti aaveche." },
    { "id": 11, "english": "Who is that man?", "banjara": "Vu maati kuun che?" },
    { "id": 12, "english": "I want to buy vegetables.", "banjara": "mann sabji leer che" },
    { "id": 13, "english": "My mother is sick.", "banjara": "mar yaadi bimar cha" },
    { "id": 14, "english": "What did you say?", "banjara": "Tu kai ko?" },
    { "id": 15, "english": "I did not hear you.", "banjara": "mann aant aai koni" },
    { "id": 16, "english": "The sun is very hot.", "banjara": "suraj ghano taato che" },
    { "id": 17, "english": "Children are playing.", "banjara": "chachar ramre che" },
    { "id": 18, "english": "Cows are grazing in the field.", "banjara": "gavdi kheteermai khad khareeche" },
    { "id": 19, "english": "Close the door.", "banjara": "darvajo band kar" },
    { "id": 20, "english": "Open the window.", "banjara": "Khitki khol / khikti vagad" },
    { "id": 21, "english": "How much is this potato?", "banjara": "ee aalure kai bhaav che?" },
    { "id": 22, "english": "This vegetable is fresh.", "banjara": "ee sabji taaja che" },
    { "id": 23, "english": "I need 1 kg of rice.", "banjara": "manne ek kilo chaaval chavche" },
    { "id": 24, "english": "Do you have milk?", "banjara": "taar kan doodh che ge?" },
    { "id": 25, "english": "The price is too high.", "banjara": "eer bhaav ghano jaada che" },
    { "id": 26, "english": "Reduce the price a little.", "banjara": "eer bhaav chanik kamm kar" },
    { "id": 27, "english": "I will not pay this much.", "banjara": "me attra bhanduni." },
    { "id": 28, "english": "Is this shop open?", "banjara": "ee dukan khulla che ge?" },
    { "id": 29, "english": "When will you close?", "banjara": "Tu kanna bandh karechi?" },
    { "id": 30, "english": "Give me change.", "banjara": "mann ek mauka de" },
    { "id": 31, "english": "Make tea for me.", "banjara": "maar vasu chaai kar" },
    { "id": 32, "english": "Wash the clothes.", "banjara": "kapda dho" },
    { "id": 33, "english": "Clean the house.", "banjara": "Ghar saaf kar" },
    { "id": 34, "english": "Cook the food properly.", "banjara": "khaayen suddo raandh" },
    { "id": 35, "english": "Serve the food.", "banjara": "Khayen ghaal" },
    { "id": 36, "english": "Water the plants.", "banjara": "jhaaduvun paani ghaal" },
    { "id": 37, "english": "Sweep the floor.", "banjara": "jammine baar" },
    { "id": 38, "english": "Turn on the light.", "banjara": "lighten chalu kar" },
    { "id": 39, "english": "Turn off the fan.", "banjara": "fanen bandh kar." },
    { "id": 40, "english": "Lock the door.", "banjara": "darvajeer taala ghal" },
    { "id": 41, "english": "Where is the bus stand?", "banjara": "bus stand kath che?" },
    { "id": 42, "english": "When will the bus come?", "banjara": "bus kanna aaveche?" },
    { "id": 43, "english": "I want to go to Hyderabad.", "banjara": "mann hyderabad en jaavnu ken chi" },
    { "id": 44, "english": "How far is it?", "banjara": "katra duur che vu?" },
    { "id": 45, "english": "The train is late.", "banjara": "rail gaadi aayen deer veejavche" },
    { "id": 46, "english": "Take a ticket.", "banjara": "Ticket leale" },
    { "id": 47, "english": "Sit near the window.", "banjara": "khitkier kann bees" },
    { "id": 48, "english": "Stand in the line.", "banjara": "line aa hubar" },
    { "id": 49, "english": "Don't push me.", "banjara": "mann dhankel math" },
    { "id": 50, "english": "Move aside.", "banjara": "bagal sarak" },
    { "id": 51, "english": "What is the time now?", "banjara": "time kai veeriche abbe?" },
    { "id": 52, "english": "It is 5 o'clock.", "banjara": "abbe paanch bajre che" },
    { "id": 53, "english": "I woke up early today.", "banjara": "me aaj jaldi uutonchu" },
    { "id": 54, "english": "I slept late last night.", "banjara": "mee kaal raath deereethi suutho tho" },
    { "id": 55, "english": "Are you ready?", "banjara": "Tu tayar chi ge?" },
    { "id": 56, "english": "Let's go now.", "banjara": "chal, abbej jaama" },
    { "id": 57, "english": "Wait for me.", "banjara": "maar vasu tham" },
    { "id": 58, "english": "Don't be late.", "banjara": "deer math kar" },
    { "id": 59, "english": "Be careful.", "banjara": "jatheneethi re" },
    { "id": 60, "english": "Walk fast.", "banjara": "jaldi chaal" },
    { "id": 61, "english": "Who called you?", "banjara": "thon kun balayo?" },
    { "id": 62, "english": "I don't know him.", "banjara": "Mann vu maalam cheni" },
    { "id": 63, "english": "He is my relative.", "banjara": "ee maaro sagaashan che" },
    { "id": 64, "english": "She is my neighbor.", "banjara": "ee maar padoosan che" },
    { "id": 65, "english": "They are good people.", "banjara": "voo aacho mannkya che" },
    { "id": 66, "english": "We are happy together.", "banjara": "hum saaterma kush cha" },
    { "id": 67, "english": "Don't fight with anyone.", "banjara": "keethi ladai math karo" },
    { "id": 68, "english": "Help the poor.", "banjara": "garib een maddat karo" },
    { "id": 69, "english": "Respect elders.", "banjara": "mootevun samman karo" },
    { "id": 70, "english": "Love children.", "banjara": "chachaarun pyaar karo" },
    { "id": 71, "english": "I am hungry.", "banjara": "Mann bookh lagrich." },
    { "id": 72, "english": "I am thirsty.", "banjara": "mann taras laagrich" },
    { "id": 73, "english": "The food is ready.", "banjara": "Khayero tayaar veegoche" },
    { "id": 74, "english": "Come inside.", "banjara": "maai aa" },
    { "id": 75, "english": "Sit here.", "banjara": "aath bees" },
    { "id": 76, "english": "What are you thinking.", "banjara": "thu kai soochrochi" },
    { "id": 77, "english": "I forgot.", "banjara": "Me bhulgo" },
    { "id": 78, "english": "I remember.", "banjara": "Mann hardeche" },
    { "id": 79, "english": "Call him.", "banjara": "Von bala." },
    { "id": 81, "english": "Greetings! to all the banjara people.", "banjara": "se gormati banjara vun ram ram" },
    { "id": 82, "english": "Sant Sevalal Maharaj.", "banjara": "Sant Sevalal Maharaj." },
    { "id": 83, "english": "You have seen his white flag flying in every thanda.", "banjara": "tam se vor dholo jhanda vader har tanderma deetez viyo" },
    { "id": 84, "english": "You have heard stories from your grandparents.", "banjara": "tam baap dadavur kan vor kahani samlez viyo" },
    { "id": 85, "english": "But do you know the complete story?", "banjara": "panan tameen puuro kahani maalam chege?" },
    { "id": 86, "english": "Do you know why he is called Maharaj?", "banjara": "tameen von Maharaj ken kashen kach ko maalam che ge?" },
    { "id": 87, "english": "Do you know what he did for our community?", "banjara": "Aapner samajeer vasu vu kaai keedoch ko maalam che ge?" },
    { "id": 89, "english": "Jai Sant Sevalal Maharaj.", "banjara": "Jai Sant Sevalal Maharaj." },
    { "id": 90, "english": "My Banjara brothers and sisters, this documentary is for you.", "banjara": "maar banjara bhai bhiyavo an bheno" },
    { "id": 91, "english": "For 220 years, our community has preserved his memory.", "banjara": "de see vees varas eeti, apner samaj vor yaadeevun gokan rakad melech" },
    { "id": 92, "english": "But many of us know only fragments of his story.", "banjara": "panan, apner ma shenduvun kahanier tukdaz malam che" },
    { "id": 93, "english": "We know he was divine.", "banjara": "apnen vu bhagvan che kethanin maalam." },
    { "id": 94, "english": "We know he reformed our community.", "banjara": "Vuz aapner samajeen sudharooch ken bhi maalam" },
    { "id": 95, "english": "We know he gave us dignity.", "banjara": "Vuz aapnen izzat darayo" },
    { "id": 96, "english": "But today, we present the complete, documented history.", "banjara": "Panan aaj, aapan voor itihaaser maieer puuro kahani ne dhekevaal cha" },
    { "id": 97, "english": "Based on historical records.", "banjara": "itihaazeermai lakmele jakon hizaabeethi." },
    { "id": 98, "english": "Government documents.", "banjara": "sarkaareer daastavvez eevur hisabeethi." },
    { "id": 99, "english": "The traditional epic Sevabhaya.", "banjara": "ek eeenaro kahaani sevabhaya" },
    { "id": 100, "english": "And oral histories passed down through generations.", "banjara": "katriko peedivuthi ee kahanevun ekeeti ek en keethe aarecha" },
    { "id": 101, "english": "This is our heritage.", "banjara": "ee aapner ithaazer mai eek heerar naai" },
    { "id": 102, "english": "This is our pride.", "banjara": "ee aper garv che" },
    { "id": 103, "english": "This is the story of Sant Sevalal Maharaj.", "banjara": "anne eez apner sant sevalal maharaj eer kahani" },
    { "id": 104, "english": "Our Maharaj was born on 15 February 1739.", "banjara": "apner maharaj | pandre february satre sao theesan nav eermai janmotho." },
    { "id": 105, "english": "This date is historically verified.", "banjara": "ee taarik peenar kittabevur mai lakmeelech" },
    { "id": 106, "english": "But his exact birthplace remains a matter of scholarly debate.", "banjara": "panan janmo jakon jaageer par aaj bhi mot aadmivurma behas vache" },
    { "id": 107, "english": "Karnataka claims Surgondankoppa in Shimoga district.", "banjara": "karnataka ma jakon shimoga jilla | surgondankoppaar mai janmoch keen kache" },
    { "id": 108, "english": "Official government records support this location.", "banjara": "sarkaareevur dastaveezurmai bhi vu jaageer naam lakhmeleche." },
    { "id": 109, "english": "Andhra Pradesh claims Sevagad in Anantapur district.", "banjara": "andhra pradesh eer mai | ananthapur jilla" },
    { "id": 110, "english": "Traditional Lambadi bards and oral histories support this location.", "banjara": "hannu keen | peenavur apnevur kahanivuthi maalam padi" },
    { "id": 112, "english": "The discrepancy reflects our community's nomadic nature during that period.", "banjara": "ee vaath apner samaj eema jaag jaag pahrer savabbaveen dikaalec." },
    { "id": 113, "english": "What matters most is not WHERE he was born.", "banjara": "Katth huyoch kajako motto vaath koni" },
    { "id": 114, "english": "But WHAT he achieved for our people.", "banjara": "panan vuu apner mankavur vasu kai kamayo kajakoneez motto vaath." },
    { "id": 115, "english": "15 February 1739 marks the birth of our greatest reformer.", "banjara": "pandre february satre soo thees an nav kajakon daado eek mooto nayak eer daadoor ken harde rejjavche" },
    { "id": 116, "english": "Sant Sevalal Maharaj came from a distinguished Rajput lineage.", "banjara": "Sant sevala maharaj | Rajput eer veeler maai thi aayoche" },
    { "id": 117, "english": "Father: Bheema Naik Ramawat Rathod.", "banjara": "Baap eer naam | Bheema Naik Ramavath Rathod" },
    { "id": 118, "english": "Mother: Dharamani Yaadi, also revered as Dharmani Mata.", "banjara": "Yaadi eer naam" },
    { "id": 119, "english": "Grandfather: Ramji Naik Rathod.", "banjara": "Dada ro naam | Ramji Naik Rathod" },
    { "id": 120, "english": "Birth name: Seva Bhaya, also known as Shiv Rathod.", "banjara": "huyo janna seva bhaya" },
    { "id": 121, "english": "The surname Rathod is significant.", "banjara": "ghar eer naam rathod kejermaaz katraiko mahatv che" },
    { "id": 122, "english": "It connects our community to the Rajput warrior clans of Chittorgarh.", "banjara": "Vu apner samaajeene | chittorgarh eer rajput yoddhavur jaatheema bhelech" },
    { "id": 123, "english": "This is our ancestral heritage.", "banjara": "ee aapnevur peedivur samman che" },
    { "id": 124, "english": "We are descendants of those who served Rana Pratap.", "banjara": "apan Maha Rana Pratap een seva karmele jakon vansaj cha" },
    { "id": 125, "english": "As a child, he herded cattle near Sirsigad.", "banjara": "nankya vetto janna" },
    { "id": 126, "english": "A simple life of service and devotion.", "banjara": "seva an bhakthi thi banchmelo jakon saada zindagi" },
    { "id": 127, "english": "Until the miracle that would establish his divinity.", "banjara": "jannaz sevalal eer maithi chamatkar baar padi" },
    { "id": 128, "english": "This event is recorded in the traditional epic Sevabhaya.", "banjara": "hannu vee jakon apner itihaaser mai chapgiche" },
    { "id": 129, "english": "Recited by Lambadi bards for centuries.", "banjara": "varsuthi gor maativur gaanavu ma reegiech" },
    { "id": 130, "english": "Young Sevalal was by a stream near Sirsigad.", "banjara": "nankya vettho janna sevalal | sirsigad eerma" },
    { "id": 131, "english": "In present-day Telangana.", "banjara": "aajer daaderma telangana ma che" },
    { "id": 132, "english": "He felt the presence of Goddess Jagadamba.", "banjara": "Voon votthe Jagadamba devi che ju anubhav vi" },
    { "id": 133, "english": "Also known as Goddess Mariamma Yaadi.", "banjara": "voonaz Devi mariamma yaadi ken bhi kach" },
    { "id": 134, "english": "He wished to offer her something.", "banjara": "voone | vu devi ne kai thoi chadavnu ken lago" },
    { "id": 135, "english": "But he possessed nothing.", "banjara": "panan vor kan kaai vetto koni." },
    { "id": 136, "english": "No food.", "banjara": "daliya chey" },
    { "id": 137, "english": "No flowers.", "banjara": "Phool bhi chey." },
    { "id": 138, "english": "No material offerings.", "banjara": "kaai chadayenez vetti koni" },
    { "id": 139, "english": "So he took mud and wheat.", "banjara": "tho haatherma dhud an gahu leedho" },
    { "id": 140, "english": "With pure devotion, he prepared sheera from mud.", "banjara": "voor bhakthi thi" },
    { "id": 141, "english": "He prepared puri from wheat.", "banjara": "an ghao thi puri banayo" },
    { "id": 142, "english": "And offered them to the goddess.", "banjara": "banatanin deevini chadayo" },
    { "id": 144, "english": "The wheat into real puri.", "banjara": "ghao jaakon asli puri re nai badalgo" },
    { "id": 145, "english": "This miracle established his divine nature.", "banjara": "ee chamatkar eethi vor mai deever nai che jako svabhaav baar padi" },
    { "id": 146, "english": "Those who witnessed this miracle understood immediately.", "banjara": "hannu veejanna kun kun dite ko vondun jannaz samaj aavgi" },
    { "id": 147, "english": "This was not an ordinary child.", "banjara": "ee saadharan chora koni ken." },
    { "id": 148, "english": "This was a divine incarnation.", "banjara": "Vu bhagvaneero amsh che keen" },
    { "id": 149, "english": "Blessed by Goddess Jagadamba herself.", "banjara": "Jagadamba deevi reej aashirvaad che keen" },
    { "id": 151, "english": "The community began to follow his guidance.", "banjara": "apan gor samaj voor vaate saamlen lagpade" },
    { "id": 152, "english": "He became Guru to our people.", "banjara": "Vuu apner guru er nai vego." },
    { "id": 154, "english": "Our roots.", "banjara": "apner jade" },
    { "id": 155, "english": "Our ancestral homeland.", "banjara": "apner baap dadvur jaag." },
    { "id": 156, "english": "The Mewar region of Rajasthan.", "banjara": "Rajasthan eer Mewar" },
    { "id": 157, "english": "The land of Chittorgarh.", "banjara": "Chittorgarh eer jammi" },
    { "id": 158, "english": "This is our ancestral homeland.", "banjara": "aper baap dada vur matrubhumi" },
    { "id": 159, "english": "Mewar region.", "banjara": "Mewar kshetr" },
    { "id": 160, "english": "Chittorgarh fort.", "banjara": "Chittorgarh eer kila." },
    { "id": 161, "english": "The land where Rana Pratap fought for freedom.", "banjara": "Rana Pratap eez jammi par aazadier vasu ladai karmeloch" },
    { "id": 163, "english": "Specifically, the Rathod clan of Chittorgarh.", "banjara": "seeti aang rathod kajakon chittorgarh eethi aamech" },
    { "id": 165, "english": "We were the logistics backbone of Rajput armies.", "banjara": "apan rajput sena vur saaman punchadeen mooreer hadkar nai vette" },
    { "id": 166, "english": "We supplied provisions to Prithviraj Chauhan's forces.", "banjara": "apan | prithviraj chauhan eer senaan bhi kai chavtoi deethethe" },
    { "id": 167, "english": "We transported grain and weapons for Rana Pratap.", "banjara": "apan rana prathap eer vasu daana an hatiyaar leen jaathe the" },
    { "id": 168, "english": "We crossed mountains and rivers with our bullock caravans.", "banjara": "apan baladure bandi bhaandleen katraiko pahad gatla an nadhivun paar karmelecha" },
    { "id": 169, "english": "We were warriors and traders.", "banjara": "apan vyapaare anne yoddha vetthe" },
    { "id": 170, "english": "This is our heritage.", "banjara": "peena thi eez apneer pehechan chi" },
    { "id": 171, "english": "This is our legacy.", "banjara": "eez aapner parampara che." },
    { "id": 173, "english": "Our community became refugees.", "banjara": "aaper samajeen daabnaake" },
    { "id": 174, "english": "We followed Rana Pratap into the forests.", "banjara": "apan rana prathap eer laar jungleuuma chalege" },
    { "id": 175, "english": "Then began our great migration south.", "banjara": "jannateez apan dhakshan bharath eer vadi dagaryaye." },
    { "id": 176, "english": "Through Malwa in Madhya Pradesh.", "banjara": "madhya pradesh eer malwa mai thi" },
    { "id": 177, "english": "Through Central India.", "banjara": "bharath eer advicha thi" },
    { "id": 178, "english": "Through the Deccan region of Maharashtra.", "banjara": "maharastra mai eer deccan ilaka thi leethanin" },
    { "id": 181, "english": "He brought 360 families from Chittorgarh.", "banjara": "chittorgarh eethi | theen sau saat katmalevun leen nikalo." },
    { "id": 183, "english": "An entire community searching for a new homeland.", "banjara": "Vu puuro samaj | navvo jaag een dhoondeen lagpade" },
    { "id": 184, "english": "Our ancestors' journey of survival.", "banjara": "hannu aapner baap dada vur xafar chaalu vi" },
    { "id": 186, "english": "The caste system denied us dignity.", "banjara": "dusar jaatheevur kann goreevur izzat gamgi" },
    { "id": 187, "english": "We were classified as outside the social hierarchy.", "banjara": "apnuune kor kyar samaj eethi duur karan deete." },
    { "id": 188, "english": "Nomadic communities were labeled Criminal Tribes by the British.", "banjara": "Voor pachhe | britisheevur aathanin" },
    { "id": 190, "english": "Our forests were confiscated.", "banjara": "apnevur jungleevuun japt keede." },
    { "id": 191, "english": "Our traditional grazing lands were restricted.", "banjara": "apeer peena vur khetari | charayer jammi shee kheench lide" },
    { "id": 193, "english": "Our women faced violence from settled communities.", "banjara": "apener yaadi bheenevun | kor kyar katraiko vela paade" },
    { "id": 194, "english": "Our culture was dismissed as primitive.", "banjara": "apan gor uen pichadiur nai vendeevur naai dheete" },
    { "id": 196, "english": "Into this oppression, he brought dignity.", "banjara": "dabamele jendun hoto izzat laayo" },
    { "id": 197, "english": "Into this despair, he brought hope.", "banjara": "niraashema hoto aasha jagayo" },
    { "id": 198, "english": "Late 1700s.", "banjara": "satre soo eer anth eer ma" },
    { "id": 199, "english": "Hyderabad city under Nizam rule.", "banjara": "Hyderabad Nizam eer heet vetthi" },
    { "id": 200, "english": "A devastating cholera epidemic struck.", "banjara": "eek bhayanak cholera mahaamaaree aayithi" },
    { "id": 201, "english": "Hundreds dying daily.", "banjara": "hazaaruusoo mankya daadi marrethe" },
    { "id": 202, "english": "The Nizam's royal physicians were helpless.", "banjara": "Nizameer kan chikitsa karevaal bhi haath paad nake" },
    { "id": 203, "english": "Traditional healers could not stop the deaths.", "banjara": "peenavur mandu thi maauth thamri koni vetti" },
    { "id": 204, "english": "Fear paralyzed the city.", "banjara": "darreethi saari sheer sheelkhal veegithi" },
    { "id": 205, "english": "Then Sant Sevalal Maharaj arrived.", "banjara": "Janna Sant Sevalal Maharaj aayo." },
    { "id": 206, "english": "With no formal medical degree.", "banjara": "kunshi mandur padai atithi koni" },
    { "id": 207, "english": "No hospital.", "banjara": "Ekki davkaan vette koni" },
    { "id": 208, "english": "No modern equipment.", "banjara": "ekki aadunik hatiyar vetti koni" },
    { "id": 209, "english": "Only his profound knowledge of Ayurveda and Naturopathy.", "banjara": "keval jhaad bhootivur gyaan ekkaz vetthi" },
    { "id": 210, "english": "He began treating cholera patients systematically.", "banjara": "eek hisaabeethi cholera thi beemar chejeen davaa deeno" }
];
